### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ignHamoude** [DarkiBoi/konas-issues#391] opened 2021-06-04 05:30 UTC
### Title  
auto gear

**Description**  
turn on auto gear and open a shulker and itll put the items in your inventory in the selected spots

**Additional info**  
you make a command with it to save your items slots

**Comment by pommmmm** [comment] 2021-06-04 06:31
Already in gamesense client, I recommend using gamesense and konas if you think you would use this often. Here’s a video demonstrating it https://youtu.be/dG85SkH6Zvw

**Comment by TransRights** [comment] 2021-06-08 10:21
Duplicate of #263

**Closed as completed by TransRights** 2021-06-08 10:21 UTC
Labels: feature
