### ISSUE TITLE
[BUG] Player Module in InvGUI rendering incorrectly.

### ISSUE THREAD

**Issue by arlomcwalter** [DarkiBoi/konas-issues#222] opened 2021-02-02 02:52 UTC
### Player Module in InvGUI rendering incorrectly.

**Description**  
When using konas, sometimes the playermodel in the players inventory GUI is rendered weirdly. Can't seem to pin down what is causing it so i assume it is some incorrect GL statement.

**Steps to reproduce:**  
1. Open the Inventory
2. View bug¿?

**Screenshots:**  
Expected:
![image](https://user-images.githubusercontent.com/17166139/106545532-71969a00-6501-11eb-87c7-d2201162c0f4.png)
Issue:
![image](https://user-images.githubusercontent.com/17166139/106545501-65124180-6501-11eb-811d-cded67969f89.png)

**Additional info**  
OS: Mac OS Big Sur
Java Version: JDK 8 v281

**Comment by DarkiBoi** [comment] 2021-02-02 20:29
Can easily be fixed, will add in next update

**Comment by gigglingbed** [comment] 2021-02-02 21:00
> Can easily be fixed, will add in next update

Sounds great, are you happy for me to close the issue?

**Comment by DarkiBoi** [comment] 2021-02-11 06:40
I'll close it myself once I've fixed it

**Comment by Walaryne** [comment] 2021-02-20 22:19
Can confirm also happening to me on Manjaro Linux.

**Comment by Walaryne** [comment] 2021-03-23 06:03
The cause of the issue is when the Inventory overlay is enabled in Containers. I spent some time to narrow it down.
If you disable it, the issue goes away completely. (Could be related to the clear/backgroundless setting, as I have that enabled too).
Hope it helps Darki.

**Comment by gigglingbed** [comment] 2021-05-07 11:10
:trollface:

**Closed** 2022-01-27 15:50 UTC
Labels: bug
