### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jj-inc** [DarkiBoi/konas-issues#241] opened 2021-02-09 20:50 UTC
### Title  
New good module for piston aura. Trap

**Description**  
if the pistonaura>>trap is enabled, then before placing the piston above the player, place a block so that he does not run away

**Comment by DarkiBoi** [comment] 2021-02-10 23:04
Duplicate of #243 Altough this issue is older, the other one follows the template better

**Closed as completed by DarkiBoi** 2021-02-10 23:04 UTC
Labels: feature
