### ISSUE TITLE
Duel sexy module

### ISSUE THREAD

**Issue by C13H16ClNOwO** [DarkiBoi/konas-issues#77] opened 2020-11-02 15:31 UTC
totem pop counter but on steroids, counts xp crystals etc, useful to know if ur outgearing someone in a duel

**Comment by DarkiBoi** [comment] 2020-11-03 18:33
Will be implemented soon :)

**Comment by DarkiBoi** [comment] 2021-05-01 19:24
Duplicate of #75

**Closed by DarkiBoi** 2021-05-01 19:24 UTC
