### ISSUE TITLE
[FEATURE] ForceFaceplace

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#245] opened 2021-02-10 23:10 UTC
### Title  
Faceplace that will work if you hold a button.

**Description**  
Make able to set 2nd key that you need to HOLD to enable Force Faceplace. Which will allow to place crystals with 0.1 minimum damage while the key is being held

**Comment by DarkiBoi** [comment] 2021-02-11 06:39
Duplicate of #199

**Closed as completed** 2021-02-11 06:39 UTC
Labels: feature
