### ISSUE TITLE
List of bugs

### ISSUE THREAD

**Issue by Katatje** [DarkiBoi/konas-issues#42] opened 2020-10-19 13:03 UTC
Webaura autoswitch switches to first slot in hotbar
Clicking in between modules in the clickgui causes both modules to toggle
Holefiller/AutoTrap fills with all blocks but surround doesnt (intended?)
CrystalAura doesnt / doesnt work on fake players?
Elytrafly mode normal doesnt work
Strafe + Longjump strafelongjumps? (intended?)
Strafe + Longjump jumps mid air when pressing w in air
Having dotted in breadcumps off doesnt work?
Chams/ESP doesnt work on slimes
PacketRenderer doesnt rotate body 
InvPreview doesnt work?
Collapsing module in clickgui still shows color picker
ClickGUI pauses game in single player
scaffold tower works as a longjump
You cant resend commands with arrow keys
ChatAppend shows in send chat history with arrow keys
Packetfly cuases single player to freeze & crash when leaving
alt manager shows servers are down while they arent

**Comment by zyktex** [comment] 2020-10-19 13:54
We aura bug has been fixed. Now it swaps to cobwebs. Clickgui has been rewritten so it dosnt really matter. AutoTrap should only use obby so that will be fixed. CA works on fake players for me, I cant reproduce that bug. Elytrafly normal is just vanilla, but you can customize the up/down/acceleration speed, to do this change the top 3 settings in elytrafly. If they're all at 1 it will be exactly the same as vanilla flight. ESP not working on slimes/ghasts will be fixed. InvPreview works for me and I can't reproduce it. Tower will be fixed. @DarkiBoi can you please look into chat stuff since you made it. Packetfly isn't supposed to work in sp ill add check to disable it if you try using it in sp. Lastly @DarkiBoi pls fix altmanager its so broken.

**Comment by zyktex** [comment] 2020-10-28 19:22
Everything here has been fixed now

**Closed by zyktex** 2020-10-28 19:22 UTC
Labels: bug
